# Generates placeholder voice lines for Chen from Assets/Audio/VO/chen/chen_lines.json,
# using the built-in Windows voice, trimmed with ffmpeg. Also writes development/Chen_VO_Script.md.
# Files are named <event>_<number>.ogg. Existing files are left alone, so real recordings
# dropped into the folder are never overwritten. Pass -Force to regenerate everything.
param([switch]$Force)
$ErrorActionPreference = 'Stop'

$projectRoot = Split-Path -Parent $PSScriptRoot
$folder = Join-Path $projectRoot 'Assets\Audio\VO\chen'
$script = Get-Content (Join-Path $folder 'chen_lines.json') -Raw | ConvertFrom-Json
$scratch = Join-Path ([System.IO.Path]::GetTempPath()) 'phantom-fray-vo'
New-Item $scratch -ItemType Directory -Force | Out-Null

Add-Type -AssemblyName System.Speech
$voice = New-Object System.Speech.Synthesis.SpeechSynthesizer
$voice.SelectVoice('Microsoft Zira Desktop')
$voice.Rate = 2

# Trim the dead air. The comms radio sound itself is on the game's Voice bus, so real
# recordings get the same treatment.
$trim = 'silenceremove=start_periods=1:start_threshold=-45dB,areverse,silenceremove=start_periods=1:start_threshold=-45dB,areverse,volume=1.6,aformat=sample_rates=22050:channel_layouts=mono'

$made = 0
foreach ($event in $script.events.PSObject.Properties) {
    $number = 0
    foreach ($line in $event.Value.lines) {
        $number++
        $target = Join-Path $folder ("{0}_{1}.ogg" -f $event.Name, $number)
        if ((Test-Path $target) -and -not $Force) { continue }
        $raw = Join-Path $scratch ("{0}_{1}.wav" -f $event.Name, $number)
        $voice.SetOutputToWaveFile($raw)
        $voice.Speak($line)
        $voice.SetOutputToNull()
        & ffmpeg -hide_banner -loglevel error -y -i $raw -af $trim -c:a libvorbis -q:a 4 $target
        if ($LASTEXITCODE -ne 0) { throw "ffmpeg failed on $target" }
        $made++
    }
}
$voice.Dispose()
Write-Host "Generated $made placeholder lines in $folder"

# The recording sheet for a voice actor or an AI voice service, written from the same JSON.
$sheet = @(
    '# Chen Voice Script',
    '',
    'Generated by `tools/generate_placeholder_vo.ps1` from `Assets/Audio/VO/chen/chen_lines.json`. Edit the JSON, not this file.',
    '',
    "**Voice:** $($script.voice)",
    '',
    "**Files:** $($script.files)",
    '',
    '| File | Line | Moment and delivery |',
    '|---|---|---|'
)
foreach ($event in $script.events.PSObject.Properties) {
    $number = 0
    foreach ($line in $event.Value.lines) {
        $number++
        $sheet += ('| `{0}_{1}.ogg` | {2} | {3} |' -f $event.Name, $number, $line, $event.Value.note)
    }
}
$sheetPath = Join-Path $projectRoot 'development\Chen_VO_Script.md'
[System.IO.File]::WriteAllLines($sheetPath, [string[]]$sheet, (New-Object System.Text.UTF8Encoding $false))
Write-Host "Wrote $sheetPath"
